### ISSUE TITLE
/lib and /api folders should not be treated equal by the startup script

### ISSUE THREAD

**Issue by anthonydahanne** [Terracotta-OSS/terracotta-core#107]
Right now, if you have a look at : 

https://github.com/Terracotta-OSS/terracotta-core/blob/master/terracotta-kit/src/assemble/server/bin/start-tc-server.sh#L58

     for pluginDir in ${PLUGIN_LIB_DIR} ${PLUGIN_API_DIR}

According to @myronkscott 

> yes, it's either or or both
> putting something in API is just like annotating with @CommonComponent
> API should not be there
> we just use annotation is I guess it wasn't caught

**Comment by ramsai1729** [comment]
I don't understand the issue, @CommonComponent approach or api jar approach is specific to a Service api & impl. One service can use @CommonComponent approach and another service can use api jar approach on the same server.

**Comment by myronkscott** [comment]
The start script needs all the classes in it's base class path.  The class loader isolation in the server handles the difference between lib and api
