### ISSUE TITLE
Passive entity reconfiguration passes the old configuration to the reconfigure call not the new one.

### ISSUE THREAD

**Issue by chrisdennis** [Terracotta-OSS/terracotta-core#1190]
https://github.com/Terracotta-OSS/terracotta-core/blob/137f5443a6222b084d7de967f1960a2f99e29112/dso-l2/src/main/java/com/tc/objectserver/entity/ManagedEntityImpl.java#L755

**Comment by myronkscott** [comment]
Fixed with merge of #1191
