### ISSUE TITLE
Where can i download BigMemory GO 4.3.6?

### ISSUE THREAD

**Issue by thomasferrero** [Terracotta-OSS/terracotta-core#1196]
Hi,

We are using BigMemory GO since quite some time.
Now that we are migrating our information system to JDK8 and Weblogic 12.2, we discovered that the version of BigMemory GO (4.0.1, ehcache-ee-2.7.1, TMC 1.1.1)  we are using is not compatible with this infrastructure: https://confluence.terracotta.org/display/release/BigMemory+4.0%2C+Ehcache+2.7+Platform+Support#BigMemory4.0,Ehcache2.7PlatformSupport-PlatformSupport. In this same wiki space we saw that we need at least BigMemory GO 4.3.6 (ehcache-ee-2.10) but **we were not able to find this version anywhere**: in the maven repositories the latest version of ehcache-ee is 2.8.5 (e.g. https://mvnrepository.com/artifact/net.sf.ehcache/ehcache-ee ), on your website the links to BigMemory Go are not working anymore e.g. http://www.terracotta.org/downloads/.

Is BigMemory GO a product you still provide?  
Can you please tell us how we can download the latest version of BigMemory GO?

Thanks for your support

**Comment by GaryWKeim** [comment]
The downloads links should be operational again.

You may want to change direction and use the 10.x OSS release going forward. It contains Ehcache 3, a new Operational Store, and the Management Console. Or you can just use Ehcache 3 (with optional clustering support) but that doesn’t include any Management & Monitoring capability.

-Gary

**Comment by thomasferrero** [comment]
Thanks.
