### ISSUE TITLE
NULL  pointer exception was thrown in Cluster environment

### ISSUE THREAD

**Issue by yurili8** [Terracotta-OSS/terracotta-core#1198]
we configure one cluster environment in our production environment. but we found one critical issue. we have to restart it on every 12 hours or it will work anymore.  And the clients could not connect the terracotta server any more and client will keep trying.
But after we restart the terracotta server, it works well again.

This is a big trouble for us, I think this may be a bug in server.

By the way, there are two nodes in the cluster environment, which runs in the docker environment, managed by docker compose. 

I put the configuraiton file in docs in the attachment. hope anybody could get us out of the trouble.

Thanks for any help.
[Terracotta.docx](https://github.com/Terracotta-OSS/terracotta-core/files/5779876/Terracotta.docx)

**Comment by chrisdennis** [comment]
Could you please re-open this in the ehcache/ehcache3 project. At the same time please make sure to include the version numbers of the products that you are using. Also please make sure any attachments are in appropriate file formats (and distinct information in distinct formats).
