### ISSUE TITLE
Configure max heap memory (Xmx) in start-tc-server.sh

### ISSUE THREAD

**Issue by shane-axiom** [Terracotta-OSS/terracotta-core#1236]
Max heap space (`-Xmx`) should be configurable via an environment variable, defaulting to the current hardcoded value of `2049m`.

https://github.com/Terracotta-OSS/terracotta-core/blob/master/terracotta-kit/src/assemble/server/bin/start-tc-server.sh#L50

We're currently having to edit the start script due to running out of heap space with the current hardcoded value.

**Comment by shane-axiom** [comment]
If anyone finds this looking for a solution to increase the heap, here's one way:

```
docker run -d --entrypoint "" terracotta/terracotta-server-oss:5.6.4 \
  bash -c "sed -i 's/-Xmx2049m/-Xmx8g/' /terracotta/server/bin/start-tc-server.sh && /terracotta/entrypoint.sh"
```

**Comment by myronkscott** [comment]
You can modify Xmx by setting JAVA_OPTS environment variable before executing the script.  Any values there will be adopted by the JVM.

**Comment by shane-axiom** [comment]
Wow, yes, I totally overlooked that `JAVA_OPTS` is specified after the defaults. So instead of the command above, one can increase the heap size like this:

```
docker run -d -e JAVA_OPTS="-Xmx8g" terracotta/terracotta-server-oss:5.6.4
```

You can see that the passed options are picked up in the JVM args (and come after the defaults, overriding them)

```
JVM arguments: [-XX:MaxDirectMemorySize=1048576g, -Xms256m, -Xmx2049m, -XX:+HeapDumpOnOutOfMemoryError, -Dtc.install-root=/terracotta/server, -Xmx8g]
```

and that the runtime memory is affected

```
2021-07-30 17:02:51.868  INFO   --- [           main] org.terracotta.console                  : Available Max Runtime Memory: 7282MB
```

Thanks!
