### ISSUE TITLE
Failure in ServiceProvider initialization causes the main thread to die but the process is kept alive because of a non interrupted thread

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-core#1253]
I am working since days to put back on track the TcDbTests project and I've bumped into what I think could be a bug in core

For the context, the project hasn't been touched since 1 year ago... So it was working 1 year ago but in 2021 there has been so many changes in EE and Angela that the tests are now impacted when I use a new kit.

So here is the issue:

There are some security tests like this one: [testNoPasswordInCredentialsSetup()](https://github.softwareag.com/matc/TcDBTest/blob/31f301dd127c7f45ba5a2a54fa9f745d83eb94e8/security/src/test/java/com/terracottatech/qa/security/server/AAA/ServerAccessControlAPSetupTest.java#L139)

They are testing that some errors are expected to see in the logs when security is badly configured.

The problem is this line: tsa.startAll(); in the test never finishes because the TSA process is stuck.

The Security ServiceProvider initialisation is failing as we can see in the logs, but the server processes are kept alive, but in a sort of zombie state because the main thread  is gone. It is like the server was supposed to stop itself and exit, but it couldn't because of the SingleThreadedTimer that is maintaining a background thread has not been stopped. 

[dump.txt](https://github.com/Terracotta-OSS/terracotta-core/files/8125761/dump.txt)
[stdout.txt](https://github.com/Terracotta-OSS/terracotta-core/files/8125762/stdout.txt)

**Comment by myronkscott** [comment]
fixed with #1255
