### ISSUE TITLE
Passive not restarted when connecting to restarted active

### ISSUE THREAD

**Issue by jd0-sag** [Terracotta-OSS/terracotta-core#131]
In active-passive tests, when both servers are configured as restartable, it is possible for a crashing active to come back up as active, again.  When this happens, the passive needs to wipe its state and re-sync from the active but this isn't happening.

Note that the most reliable way forward may be to avoid this situation, altogether.  That is, change the election weight heuristics so that this can't happen:  force the active to always be promoted from an existing passive by forcing the newly-restarted server to lose the election.  After all, this case is probably limited to testing environments (since the restart has to happen quickly), offers no real benefit (the active and passive would have nearly the same progress), is less deterministic, and creates a new case (being zapped this late into a run).

The weight heuristics used in the election currently have the following order:

1. TransactionCountWeightGenerator - progress through transaction sequence
2. ChannelWeightGenerator - number of connected clients
3. ServerUptimeWeightGenerator - time since process started
4. RandomWeightGenerator - random number

We could change this behaviour by adjusting the order of the heuristics:

1. ServerUptimeWeightGenerator
2. ChannelWeightGenerator
3. RandomWeightGenerator

That way, uptime would dominate, meaning that fail-over would happen 100% of the time.  ChannelWeightGenerator is a meaningful tie-breaker during start-up.  RandomWeightGenerator is still there to handle the case where all coins land on their edges.

**Comment by jd0-sag** [comment]
Changing this election heuristic, alone, is insufficient to solve this problem.  A restartable server will still try to resume its previous state.

While we could handle this "first connection to cluster since JVM started" specially, this would need to be done carefully as to not break the single-active case, nor break the handling of an active reconnecting to a passive after a short network interruption.

**Comment by myronkscott** [comment]
The PASSIVE-STANDBY node is running into Condition #2 in the following code comment in StateManagerImpl

      // Condition 1 :
      // Obviously an issue.
      // Condition 2 :
      // This shouldn't happen normally, but is possible when there is some weird network error where A sees B,
      // B sees A/C and C sees B and A is active and C is trying to run election
      // Force other node to rerun election so that we can abort
      // Condition 3 :
      // We don't want new L2s to win an election when there are old L2s in PASSIVE states.

However, we are under a t server scenario, not 3.  Looking for proper resolution.
