### ISSUE TITLE
`start-tc-server.sh` fails to handle spaces in install directory path

### ISSUE THREAD

**Issue by cljohnso** [Terracotta-OSS/terracotta-core#178]
The present CloudBees-based build system for Ehcache performs the builds in a JDK-specific work directory.  Each of the working directories has at least one space in at least one directory name -- for example, `/scratch/jenkins/workspace/ehcache3-pull-requests/jdk/Sun JDK 1.6 (latest)/label_exp/standard`.  The builds are failing (hanging) in clustered:integration-test for tests dependent on starting a server (using `start-tc-server.sh`) -- the `PLUGIN_CLASSPATH` is not being properly built when the install directory contains a space.

This failure is presently blocking successful builds of PR ehcache/ehcache3#1039.

**Comment by jd0-sag** [comment]
So, the problem is with the use of the "for ... in ..." iterator, in setPluginClasspath?

It looks like all their "in" clauses need to be wrapped in quotes (as well as the corresponding "-e").

Otherwise, the construction of the classpath argument looks correct.  I will put something together and post a PR so you can verify that this is what was expected.

**Comment by cljohnso** [comment]
The following is what I hacked in to a local copy to get it to successfully start; I can't speak to its completeness.  It includes some `echo` lines for observing behavior.

```
cljo@MCCLJO01:bin $ diff ~/GitHub/terracotta-core/terracotta-kit/src/assemble/server/bin/start-tc-server.sh start-tc-server.sh
50a51,54
> echo "TC_INSTALL_DIR=${TC_INSTALL_DIR}"
> echo "PLUGIN_LIB_DIR=${PLUGIN_LIB_DIR}"
> echo "PLUGIN_API_DIR=${PLUGIN_API_DIR}"
> 
72c76
<     for pluginDir in ${PLUGIN_LIB_DIR} ${PLUGIN_API_DIR}
---
>     for pluginDir in "${PLUGIN_LIB_DIR}" "${PLUGIN_API_DIR}"
74c78,79
<         if [ -e ${pluginDir} ]
---
>         echo "  pluginDir=${pluginDir}"
>         if [ -e "${pluginDir}" ]
76c81
<             for jarFile in ${pluginDir}/*.jar
---
>             for jarFile in "${pluginDir}"/*.jar
77a83
>                 echo "    [PLUGIN] jarFile=${jarFile}"
82c88
<             for jarFile in ${TC_INSTALL_DIR}/server/lib//slf4j*.jar
---
>             for jarFile in "${TC_INSTALL_DIR}"/server/lib//slf4j*.jar
83a90
>                 echo "    [INSTALL] jarFile=${jarFile}"
94a102,103
> echo "PLUGIN_CLASSPATH=${PLUGIN_CLASSPATH}"
> 
```

**Comment by jd0-sag** [comment]
Yeah, that is pretty much exactly what I have.

The only issue I have is with the Windows side of the change, since I have no good way to verify it and I am mostly flying blind.  I will ask one of the Windows-using guys on the team to quickly verify that it works, once I have it.

**Comment by cljohnso** [comment]
You should get either @gibsong or @cschanck to take a look -- they both have Windows platforms readily available.
