### ISSUE TITLE
PassthroughServerProcess.destroy does not call CommonServerEntity.destroy

### ISSUE THREAD

**Issue by cljohnso** [Terracotta-OSS/terracotta-core#190]
When `destroy` or `tryDestroy` is called on a client-side entity, one expects the `destroy` method on the server-side entity to be called.  This is not happening when using `PassthroughServer` -- the call to `CommonServerEntity.destroy` is missing from `PassthroughServerProcess.destroy`.

**Comment by myronkscott** [comment]
This issue probably belongs in the tc-api repo.

**Comment by cljohnso** [comment]
Wrong project
