### ISSUE TITLE
Building the server requires svn on the path

### ISSUE THREAD

**Issue by lorban** [Terracotta-OSS/terracotta-core#225]
Otherwise, the build fails with:

```
[ERROR] Failed to execute goal org.terracotta:maven-forge-plugin:1.2.13:manifest (default) on project terracotta: Execution default of goal org.terracotta:maven-forge-plugin:1.2.13:manifest failed: Execute failed: java.io.IOException: Cannot run program "svn": error=2, No such file or directory -> [Help 1]
```

**Comment by akomakom** [comment]
Making some adjustments to maven-forge-plugin

**Comment by akomakom** [comment]
Can someone refresh my memory about this, I think I fixed it but... where was this happening?

**Comment by myronkscott** [comment]
If you run `mvn clean install` in tc-core, you need svn installed in order to get a clean build even though we do not use svn for this build.  I believe it was related to maven-forge-plugin trying to discover build information but that part I am less clear about.
