### ISSUE TITLE
Create succeeding on maintenanceLock.writeLock().tryLock() failure interacts badly with the clustered locking behavior

### ISSUE THREAD

**Issue by chrisdennis** [Terracotta-OSS/terracotta-core#234]
The new changes to have create() succeed when a entity is fetched by suceeding when the tryLock() fails have unfortunate interactions with the way the clustered lock manager works.  A simple loop such as this: 
```java
while (true) {
  try {
    return reference.fetchEntity();
  } catch (EntityNotFoundException e) {
    try {
      reference.create(null);
    } catch (EntityAlreadyExistsException f) {
      //ignore
    }
  }
}
```
loops indefinitely because of the way the lock manager behaves.  Sequence of operations is as such:

 1. Entity fetch requests a read lock, and the client is awarded greedy read.
 2. Entity is absent, so the lock is released, but the client keeps the greedy read.
 3. Entity create call tryLock(WRITE), the client side lock manager sees the greedy read, triggers a recall of it's greedy hold, and then returns false for the timeout, since the lock is not "available".  Recall completes and the lock becomes free.  A subsequent tryLock now would suceed, but:
 4. State is now "empty" again, loop back to step 1, and we are doomed.

To me there are two simple solutions here:
 1. Disable greedy locking in the server by default.
 2. Move the create tryLock to have a timeout (which I believe behaves differently, and will wait for the recall to complete, and then attempt the lock without failing).

**Comment by jd0-sag** [comment]
If disabling greedy locking  would give us the right behavior, we should probably just do that.

The plan is to eventually remove the lock manager, altogether, since it no longer aligns with what we want.

**Comment by jd0-sag** [comment]
I will take ownership of this and experiment with removing the greedy lock support.
