### ISSUE TITLE
Exception thrown by server when multiple clients try to create a clustered cache

### ISSUE THREAD

**Issue by kcleereman** [Terracotta-OSS/terracotta-core#265]
When attempting to create a common clustered cache with four clients we sometimes run into exception_server, attached.  This occurs most frequently when all clients are started at the same time, and rarely if ever occurs if there is a 20 second delay between client initialization.

Possibly related to this is that our timeout for cache initialization (10 seconds) is not sufficient for a clustered cache, meaning that we need to catch the TimeoutException and retry client initialization - this is exception_client1.  This exception is ALWAYS thrown by at least one client.  Less frequently exception_client2 will be thrown as well, although most often this isn't thrown unless the server crashes.

[exception_client2.txt](https://github.com/Terracotta-OSS/terracotta-core/files/374043/exception_client2.txt)
[exception_server.txt](https://github.com/Terracotta-OSS/terracotta-core/files/374044/exception_server.txt)
[exception_client1.txt](https://github.com/Terracotta-OSS/terracotta-core/files/374045/exception_client1.txt)

**Comment by jd0-sag** [comment]
The key point here is that the server exception shows an asymmetric channel removal:
com.tc.objectserver.core.impl.ManagementTopologyEventCollector.clientDidDisconnect(ManagementTopologyEventCollector.java:204)

The assertion is triggered because we tried to remove a client which had never registered as connected.

**Comment by anthonydahanne** [comment]
I just had something similar, with 2 clients.
Same server stacktrace, clients did not output any errors
