### ISSUE TITLE
Provide a way to plug in Xms and Xmx into the server startup script

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-core#266]

**Comment by ramsai1729** [comment]
JAVA_OPTS can be used to override default values. 

````
# the solaris 64-bit JVM has a bug that makes it fail to allocate more than 2GB of offheap when
# the max heap is <= 2G, hence we set the heap size to a bit more than 2GB
${JAVA_COMMAND} -Xms2049m -Xmx2049m -XX:+HeapDumpOnOutOfMemoryError \
   -Dcom.sun.management.jmxremote \
   -Dtc.install-root="${TC_INSTALL_DIR}" \
   -Dsun.rmi.dgc.server.gcInterval=31536000000\
   ${JAVA_OPTS} \
   -cp "${TC_INSTALL_DIR}/server/lib/tc.jar:${PLUGIN_CLASSPATH}" \
   com.tc.server.TCServerMain "$@"
 exitValue=$?
 start=false;
```

**Comment by jd0-sag** [comment]
I verified that the following precedence rules seem to be applied (so @ramsai1729's suggestion is a way that we can override the arguments):

- The **LAST** entry on the command-line overrides previous values (`-Xms64m -Xmx64m -Xms256m -Xmx256m` will give an answer of 256m)
- `_JAVA_OPTIONS` env var will override options on the command line (`export _JAVA_OPTIONS="-Xms512m -Xmx512m"`, before the previous example will change the answer to 512m)

**Comment by myronkscott** [comment]
Workarounds in place.  May be part of a later scripting redesign.
