### ISSUE TITLE
Bad ordering in calls to IMonitorigProducer.removeNode()

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-core#297]
This bug is blocking us. 

__This bug is only in voltron: the passthrough system works fine__

When a client leaves, calls to `IMonitorigProducer.removeNode()` are done first on the client path and then on the fetch path. It should be the opposite.

Currently we have in the logs the following calls:

`[0] removeNode() platform/clients/2`

and then:

`[0] removeNode() platform/fetched/2org.terracotta.management.entity.tms.client.TmsAgentEntityVoltronTmsConnection:TestTerracottaConnection`

This throws an exception in our code because we cannot find the client associated to the unfetch because it has been removed already.

`org.terracotta.exception.EntityUserException: Entity: org.terracotta.management.entity.tms.client.TmsAgentEntity:VoltronTmsConnection:TestTerracottaConnection exception in user code: Invalid tree state: missing PlatformConnectedClient at [platform, clients, 2]`

In case of a client disconnection the ordering should be:

1. first remove the fetch info
2. then remove the client

**Comment by myronkscott** [comment]
Technically, this is not what is happening in the underlying implementation.  Since the entity is not being explicitly unfetched, the client disconnect is forcing the server to "clean-up" fetched entities after the disappearance of the client.  It should be possible to give the illusion of strict ordering the scenario that you describe but before we implement that, is it possible for (and/or appropriate) for TMS code to be more tolerant of indeterminate order in tree mutations.  This is not a request but more of a question.

**Comment by mathieucarbou** [comment]
I had a look to see whether we have an alternative or not and we don't since we do not track anymore the tree mutations like before with the change to the consumer id.

Basically, we need at the end to create some notification objects with the data they relates to and once a client node is removed, we cannot keep a reference to it in the eventual case of a fetch removal after.

Also, logically it does not make sense to have some fetch objects kept in the tree if the client is not there since it leaves the tree in an inconsistent state, which is the thing we want to avoid: the tree needs to be as reliable as possible so that we can query it and built a topology without crashing and in a reliable way.

**Comment by jd0-sag** [comment]
After talking about this, we decided that the way forward is to defer the "client disconnected" event (node removal) until the platform has seen the corresponding entity disconnect calls arrive.

This means that an `IMonitoringProducer` implementation which _does_ directly interpret the nodes added by the platform will not observe a point where a client-entity fetch relationship is missing either  its corresponding client or entity.

**Comment by jd0-sag** [comment]
Resolved by f90594a6ff8ada545f563a88299cfe2fc8d25038
