### ISSUE TITLE
LocalMonitoringProducer needs to send best-efforts data to the active

### ISSUE THREAD

**Issue by jd0-sag** [Terracotta-OSS/terracotta-core#312]
When in passive mode, `LocalMonitoringProducer` caches `addNode`/`removeNode` calls _and_ sends them to the active.  `pushBestEffortsFromShim`, on the other hand, does nothing when in passive mode.

While it is probably inappropriate to cache this information (although we could easily cache the most recent stat for each name, if it is considered useful), we definitely should pass this information to the active.

Note that this will require some kind of throttling heuristic since there is a network cost to doing this.  While we may not be able to feasibly create a true back-pressure mechanism from the lower levels (how to balance these messages against other messages is also a concern when trying to detect back-pressure), we can minimally apply some kind of static throttling heuristic or create an internal timer to flush this data on a periodic basis.

Ideally, we want to drop messages which arrive too quickly but _eventually_ send the most recent stats (technically, this "most recent" requirement is optional but it would be ideal).

**Comment by jd0-sag** [comment]
While we could easily just send _all_ data over the wire, we would generally like to avoid saturating the link from the passive to the active.

Ideally, we would be able to plumb some notion of the back-pressure from the network layer higher into the stack but that currently isn't an option.

A reasonable midway point would be to use the `SingleThreadedTimer` to only periodically send the most recently produced data for a given stat key.  It would give us an ability to throttle the data, but only statically.

This approach would minimize the network chatter and would also allow us to batch the periodically-sent messages.

**Comment by jd0-sag** [comment]
The plan for this is to approach it in 2 phases, to keep the change consumable:

1. Cache a fixed-sized backlog of best-efforts data.  New entries to an existing key will over-write the old.  Once the backlog gets to a fixed constant size, the entire cache will be flushed to a message and sent to the active.  Note that this means data won't be sent until the cache reaches a certain size.  This allows basic functionality while introducing the messaging logic required for the batch of best-efforts data.
1. Hook into `SingleThreadedTimer` to run a constant delay after the first entry is added or, in case there is still data to be flushed when the timer slice ends, a constant delay later.  When the timer runs, it will remove a fixed-sized number of entries (the "timer slice") and send them to the active.  How this selection is done is still to be determined but will likely be implemented as a queue of references to updated cache entries so that all the entries are eventually visited.  This will have the effect of reordering the updates since an update to a still-cached value will result in the new value being sent when the old value was scheduled (its later queued entry being ignored).  The value of this is that we will still make progress through all the data, will never send stale (shadowed) data, and will still be able to send snapshots of rapidly-changing data.

When promoted to active, the timer will be cancelled and all existing data in the cache will be flushed to the underlying `IStripeMonitoring` implementation before being discarded.

An open question is how to handle the case where we can't keep up.  While the design will implicitly discard old data from over-written keys, it could have issues with cases where lots of keys are only written once (as those grow the cache).  For now, the plan is to drop these new writes if the cache grows to a certain maximum threshold.  Ideally, we would discard the oldest entries but that is more overhead and complexity in the critical path for what is, by definition, a "best-efforts" mechanism.  Additionally, this kind of usage pattern is not expected (since each entity is likely to only have a few keys it re-uses).

While we could use a simple ring buffer for this approach, it would be vulnerable to barging:  several updates to the same key, shadowing each other, but over-writing unique data.  We may re-open this, in the future, if we determine that it addresses performance concerns or is simpler to maintain in light of actual usage modes.

**Comment by jd0-sag** [comment]
FYI:  @anthonydahanne @mathieucarbou

**Comment by mathieucarbou** [comment]
Thanks! We need that also so that statistics and notifications send from passive can be read by the tms.

**Comment by mathieucarbou** [comment]
Update: spoken to @lorban : impacts on the UI (delays) are acceptable (if for a few seconds, no more)

**Comment by jd0-sag** [comment]
My plan here is to use 1 second as the maximal delay.  The only time it will take longer than that is if the key set being updated is huge so it would take several batches.  Presumably, that shouldn't happen since the set of keys being updated should be small (frequent updates to a small number of keys - this will fit nicely and the delay mechanism will allow over-writing coalescing of rapidly updated keys to avoid sending already-stale data to the active).

Ideally, we would find a way to plumb the back-pressure up to this point in the stack but that doesn't appear to be feasible, at the moment.
