### ISSUE TITLE
Default tc config misses default offheap resources

### ISSUE THREAD

**Issue by aurbroszniowski** [Terracotta-OSS/terracotta-core#313]
When starting the server, the default config is 'default-config.xml' which doesn't define offheap resources.
Therefore we cannot create an ehcache clustered client (the clustered tier has no offheap resource).
If this is a conscious decision, feel free to close this issue but this feels to me like a usability issue (compared to Terracotta 4 which allocates 2GB of offheap by default).

If the goal is to force the user to define offheap resources, then no default config should be provided and an early failure should happen. Currently the server is authorized to start with no user-defined config but can not be used with the default config.

**Comment by jd0-sag** [comment]
My assumption is that this is a packaging concern regarding how the EhCache kit is built.  They probably just need a default config which contains that.

I don't think that the default platform kit even has offheap services so I would have assumed that specifying that would cause a start-up failure, if the downstream components weren't also added.  terracotta-core, on its own, knows nothing about EhCache or any specific packaging or use-case.
