### ISSUE TITLE
identifier for "fetch" not unique when calling addNode/removeNode

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-core#337]
The voltron identifier passed to the calls to IStripeMonitoring addNode/removeNode when a fetch or unfetch happen should be more unique. Currently it is a composition of client id and entity name/type so it does not support when the same client fetches several times the same entity.

The identifier should much more be as unique as the client descriptor.

Note:  this is blocking blocking M&m Ehcache PR ehcache/ehcache3#1555

Update:

One of the problem we have is that removeNode is called, and then the topology is updated accordingly, by removing all fetches information for the client/entity. But the issue is that in reality, there are still some fetched alive and the topology is then inconsistent and it crashed for future calls to removeNode or else when we update the topology or when some operations are done in relation to a fetch entry that is not there anymore.

**Comment by jd0-sag** [comment]
Oddly enough, `ManagementTopologyEventCollector` accounts for this possibility that there may be multiple fetches of the same entity from the same client but it only tracks this to assert that the calls are balanced.  It still passes the calls on to the underlying service interface with the colliding identifiers.

Hopefully, I can fix this such that this extra accounting also becomes redundant and can be removed.
