### ISSUE TITLE
Stages need a better algorithm for finding the shortest queue

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-core#350]
Currently, the stage implementation uses a very crude and brute force method of finding the shortest queue.  A different method is needed that returns quickly and has a high level of accuracy in finding the right target.

**Comment by cschanck** [comment]
Hey, could you point at the general area of the code? Light reading this weekend.

**Comment by myronkscott** [comment]
https://github.com/Terracotta-OSS/terracotta-core/blob/master/common/src/main/java/com/tc/async/impl/StageQueueImpl.java#L182

**Comment by cschanck** [comment]
Thanks

**Comment by cschanck** [comment]
PR pushed: https://github.com/Terracotta-OSS/terracotta-core/pull/557

**Comment by cschanck** [comment]
Myron had 2 good suggestions, fast path the singleton case, and put the property in the TCProperties.

**Comment by cschanck** [comment]
Merged
