### ISSUE TITLE
AssertionError when setting up a large cluster

### ISSUE THREAD

**Issue by kcleereman** [Terracotta-OSS/terracotta-core#360]
When setting up a connection to a large cluster, the client will throw a TimeoutException because it takes longer than expected for the server to allocate the cluster. Previously we could work around this by establishing the connection in a retry loop, but now the server will crash with an AssertionError if we try to reestablish the connection. (When setting up a small cluster we don't get a TimeoutException and so we don't get an AssertionError)

The exception thrown by the server:

com.tc.util.TCAssertionError: Assertion failed
at com.tc.util.Assert.failure(Assert.java:55)
at com.tc.util.Assert.eval(Assert.java:64)
at com.tc.util.Assert.assertTrue(Assert.java:85)
at com.tc.objectserver.handler.ProcessTransactionHandler$1.handleEvent(ProcessTransactionHandler.java:98)
at com.tc.objectserver.handler.ProcessTransactionHandler$1.handleEvent(ProcessTransactionHandler.java:91)
at com.tc.async.impl.StageQueueImpl$HandledContext.runWithHandler(StageQueueImpl.java:502)
at com.tc.async.impl.StageImpl$WorkerThread.run(StageImpl.java:197)

Client code to reproduce the exception (note the cluster size of "(64, MemoryUnit.GB)" - this size will throw the TimeoutException, but if we only allocate 8gb then we don't get the TimeoutException or the AssertionError):

    final URI clusterURI = URI.create("terracotta://localhost:9510/cachemanager");
    PersistentCacheManager cacheManager = null;

    final CacheManagerBuilder<PersistentCacheManager> clusteredCacheManagerBuilder =
        CacheManagerBuilder.newCacheManagerBuilder()
            .with(ClusteringServiceConfigurationBuilder.cluster(clusterURI)
                .autoCreate().defaultServerResource("primary-server-resource")
            )
            .withCache("clustered-cache",   CacheConfigurationBuilder.newCacheConfigurationBuilder(Long.class, byte[].class,
              ResourcePoolsBuilder.newResourcePoolsBuilder()
                  .with(ClusteredResourcePoolBuilder.clusteredDedicated(64, MemoryUnit.GB))));
    while (true) {
      try {
        cacheManager = clusteredCacheManagerBuilder.build(true); // this throws the TimeoutException
        break;
      } catch (Exception e) {
        e.printStackTrace();
      }
    }

**Comment by jd0-sag** [comment]
At first glance, this looks like the assertion is triggered when we unexpectedly fail to send a response to the long-running invoke since the client has been disconnected.

This should be safe to commute to a log, instead.  The tricky part will be figuring out how to effectively test the case.

**Comment by jd0-sag** [comment]
It turned out to be pretty easy to augment one of our existing tests to create this failure.  Any long-running task makes this possible since it gives the client an opportunity to force close the connection which cases this assertion failure on the server.
