### ISSUE TITLE
/com/tc/config/schema/setup/default-config.xml is not valid

### ISSUE THREAD

**Issue by aurbroszniowski** [Terracotta-OSS/terracotta-core#371]
Using the latest available version (5.0.12-beta) starting the terracotta server without providing a tc-config will fallback on the default /com/tc/config/schema/setup/default-config.xml and will give the following error:

```
Fatal Terracotta startup exception:

 com.tc.config.schema.setup.ConfigurationSetupException:
*******************************************************************************
The configuration data in the base configuration from Java resource at '/com/tc/config/schema/setup/default-config.xml', relative to class com.tc.config.schema.setup.StandardXMLFileConfigurationCreator does not obey the Terracotta schema:
  [0]: Line 24, column 13: cvc-complex-type.2.4.a: Invalid content was found starting with element 'services'. One of '{"http://www.terracotta.org/config":plugins, "http://www.terracotta.org/config":entities, "http://www.terracotta.org/config":tc-properties, "http://www.terracotta.org/config":servers}' is expected.

*******************************************************************************
```

**Comment by jd0-sag** [comment]
I still wonder what the value in having the default config actually is.  It seems like starting with a default config is always a mistake since it can't really do anything.

**Comment by aurbroszniowski** [comment]
You should consider opening a discussion, either to change the implementation design to make the default config meaningful (The defaults configs played a big role in the easiness of adoption in previous Terracotta/Ehcache versions, you can expect upgrading users to try the new version without tc-config), or to remove totally the default tc config and make the server fail at startup without it, but with an explicit error.
