### ISSUE TITLE
Need a way to log build information of plugins

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-core#378]
Plugins should provide build information that the platform can read in a standard way so that it can be logged or presented to M&M.

**Comment by myronkscott** [comment]
@ljacomet, @anthonydahanne any thoughts on how to best to achieve this if deemed important?  Platform itself uses https://github.com/Terracotta-OSS/terracotta-core/blob/18cc70d5384316c9da52db314c6bf56e31671de1/common/src/main/java/com/tc/util/ProductInfo.java

**Comment by anthonydahanne** [comment]
I'm not sure I exactly get what you're suggesting @myronkscott . Do you suggest all plugins implementers should use ProductInfo and the associated .properties file to describe their plugins ?

In that case, I'd suggest replacing System.out with a log appender, and/or exporting the ProductInfo as a simple POJO MnM could parse.

Could it even be that when entities are created, MnM receive the creation event, including all that ProductInfo information about the plugins that shipped those entities ? (cc @mathieucarbou )

**Comment by myronkscott** [comment]
logging is a separate issue.  We just need the information from plugins.   More wondering what format and where?  META-INF? POJO? resource file?

**Comment by mathieucarbou** [comment]
@myronkscott : what do you mean by "plugins" ? Do you only refer to the extended services such as offheap or a product ?

For example, in M&M, this is one "plugin" in a business point of view ( one product), but which contain several services / service providers of entities working together.

I think it is the same for Ehcache: its 1 product, having several services / service providers / entities working together.

So the product info might somehow refer much more to a "distribution" build than technical modules.

So is it some metadata installed on a distribution output that we need to have or some metadata describing each technical voltron services / plugins / providers ?

**Comment by myronkscott** [comment]
i believe every jar in the plugins directory should have version and build information.  It may be overkill but better more information than too little.  So anything that presents as extended config, service, or entity should have build and version information embedded and accessible somewhere so that when discovery happens, platform can access it.

**Comment by mathieucarbou** [comment]
make sense! I think the `MANIFEST.MF` file that is already there in jar file aims to do that, and adding some entries through maven with some information is quite trivial also :-)

**Comment by ljacomet** [comment]
Having had a discussion with @myronkscott I believe we need to move away from the `build-data.txt` as the basis of all that information.
Instead using `MANIFEST.MF` of jars deployed in plugins fits better the extensibility of the platform.

However, I do not think this is a high priority issue and we could have current official platform build provide the proper build-data.txt - talking about Ehcache 3 here for example.

**Comment by myronkscott** [comment]
This has been determined as not needed.  Will re-open if we determine that it is needed at a later point.
