### ISSUE TITLE
Entity creation event not send to M&M after a failover

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-core#405]
When a failover occurs, @jd0-sag explained me (and hence I coded that) that addNode() calls are made on the new active with the PlatformEntity false isActive set to false (when replaying the tree), meaning that passive entities are added in the tree, then some addNode will be called again with this time PlatformEntity flag isActive set to true, when active entities will be created by the new active.

This works fine with passthrough. We receive for the same entity 2 addNode, first one with isActive=false (when replaying the tree) then second one (isActive=true) when new active entity is created.

With Galvan, this does not work.

We receive the replay, but we do not receive events after active entities are created.

So server crashes because we cannot record clients fetching entities that are not in the topology tree because we didn't receive any addNode() call for them.

```
.monitoring.IStripeMonitoringPlatformListenerAdapter - [0] addNode(testServer1, [], platform)
.monitoring.IStripeMonitoringPlatformListenerAdapter - [0] addNode(testServer1, [platform], clients)
.monitoring.IStripeMonitoringPlatformListenerAdapter - [0] addNode(testServer1, [platform], entities)
.monitoring.IStripeMonitoringPlatformListenerAdapter - [0] addNode(testServer1, [platform, entities], org.terracotta.management.entity.management.client.ManagementAgentEntityManagementAgent)
.monitoring.TopologyService - [0] serverEntityFailover(testServer1, PlatformEntity{isActive=false, typeName='org.terracotta.management.entity.management.client.ManagementAgentEntity', consumerID=2, name='ManagementAgent'})
.monitoring.MonitoringServiceProvider - [2] onEntityDestroyed()
.monitoring.IStripeMonitoringPlatformListenerAdapter - [0] addNode(testServer1, [platform, entities], org.terracotta.management.entity.sample.client.CacheEntitypet-clinic/clients)
.monitoring.TopologyService - [0] serverEntityFailover(testServer1, PlatformEntity{isActive=false, typeName='org.terracotta.management.entity.sample.client.CacheEntity', consumerID=4, name='pet-clinic/clients'})
.monitoring.MonitoringServiceProvider - [4] onEntityDestroyed()
.monitoring.IStripeMonitoringPlatformListenerAdapter - [0] addNode(testServer1, [platform, entities], org.terracotta.management.entity.tms.client.TmsAgentEntityFailoverIT)
.monitoring.TopologyService - [0] serverEntityFailover(testServer1, PlatformEntity{isActive=false, typeName='org.terracotta.management.entity.tms.client.TmsAgentEntity', consumerID=1, name='FailoverIT'})
.monitoring.MonitoringServiceProvider - [1] onEntityDestroyed()
.monitoring.IStripeMonitoringPlatformListenerAdapter - [0] addNode(testServer1, [platform, entities], org.terracotta.management.entity.sample.client.CacheEntitypet-clinic/pets)
.monitoring.TopologyService - [0] serverEntityFailover(testServer1, PlatformEntity{isActive=false, typeName='org.terracotta.management.entity.sample.client.CacheEntity', consumerID=3, name='pet-clinic/pets'})
.monitoring.MonitoringServiceProvider - [3] onEntityDestroyed()
.monitoring.IStripeMonitoringPlatformListenerAdapter - [0] addNode(testServer1, [platform], state)
.monitoring.TopologyService - [0] serverStateChanged(testServer1, PASSIVE)
.monitoring.IStripeMonitoringPlatformListenerAdapter - [0] addNode(testServer1, [platform], fetched)
// we do not have additional addNode() with isActive=true, like Jeff explained me and like it is on passthrough
```

Here are the complete server logs with all M&M traces

[server0.stdout.log.txt](https://github.com/Terracotta-OSS/terracotta-core/files/658506/server0.stdout.log.txt)

[server1.stdout.log.txt](https://github.com/Terracotta-OSS/terracotta-core/files/658507/server1.stdout.log.txt)

**Comment by mathieucarbou** [comment]
CC @anthonydahanne 

This is blocking for us (https://github.com/Terracotta-OSS/terracotta-platform/pull/243) 

I developed based on the discussions I had with @jd0-sag and the understanding that there should be 2 addNode() calls: one for the replay of the passive entity in the new active (isActive=false) and another call once the active entity is created (isActive=true).

So if there is a change of behavior, I need to know asap to change out implementation.

**Comment by myronkscott** [comment]
I believe what you describe is the desired sequence.  I'll look into why the correct sequence is not being reported as soon as possible.
