### ISSUE TITLE
Platform event ordering does not allow a client to re-expose management metadata

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-core#412]
Since latest release, platform event ordering has changed and now is (see @myronkscott comment on #409 ):

1.  Election manager declares winner (ACTIVE-COORINDATOR logging that you see)
but the server is not fully active yet.  That log message only starts the process
2.  Passive entities are removed
3.  Active entities are created
4.  Server declared active to M&M and cached tree replayed
5.  Reconnect window opens
6.  Clients reconnect
7.  Reconnect window closes. transition completed to active server. now ready to process new transactions

@jd0-sag told me that each clients having some states (i.e. management registry, tags, etc.) to re-expose after a failover should do so by using the `handleReconnect()` callback. And this is what we did.

Now, the issue is that platform currently tells us about reconnected clients AFTER the reconnect, and thus the topology is not yet constructed. So we have some clients that push some states in `handleReconnect()` but the monitoring service cannot accept them since the platform didn't tell us about these client descriptors before.

If you look at the attached logs, you'll see  that calls to `onReconnect(...)` happens BEFORE calls to `addNode(...)`. So we cannot attach these states to the reconnecting client because we are not aware of them before through the `IStripeMonitoring`

[stdout.log.server0.txt](https://github.com/Terracotta-OSS/terracotta-core/files/665114/stdout.log.server0.txt)
[stdout.log.server1.txt](https://github.com/Terracotta-OSS/terracotta-core/files/665113/stdout.log.server1.txt)

I see different proposals to fix that:

1. platform implement a `onReconnected()` callback on client-side that we can use to know when a client has finished reconnected (this was my first proposal before @jd0-sag told me to use `handleReconnect()`). And from a user point of view, this is really what I want: I'd like to now, on a client-side, when the endpoint has reconnected. We typically do not care about the reconnect data phase with M&M.

2. platform sends us events about reconnecting clients before `handleReconnect()` => which was our expectation based on what @jd0-sag told me

3. M&M push these reconnect data into a queue in the monitoring service, and when platform sends us the event saying a client has reconnected, we dequeue the reconnect data and process it. => it could create a leak and queue could grow if we miss some events for a reason

4. platform tells us about the end of the failover phase, when the reconnect window closes, so that we can dequeue the buffered reconnect data and clear the remaining ones

5. ... ideas welcomed...

Please let us know what would be the __quickest__ way for us to fix it so that we can finish that.

**Comment by myronkscott** [comment]
Please test on this branch of tc-core

https://github.com/myronkscott/terracotta-core/tree/monitor_reordering_again

This should enable the ordering 1-7 I listed above.  If I understand correctly this will provide the functionality you desire.

**Comment by mathieucarbou** [comment]
thanks! @myronkscott what is the ordering of build now with galvan ? can I only build tc-core snapshot and still depend on latest galvan release ?

**Comment by mathieucarbou** [comment]
@myronkscott @jd0-sag : I put that in tc-platform:

```
    <terracotta-core.version>5.2-SNAPSHOT</terracotta-core.version>
    <galvan.version>1.2-SNAPSHOT</galvan.version>
```

I rebuilt galvan and tc-core (your branch), ran the tests, but nothing changed. I am wondering if galvan is running the tc-core snapshot... ?

**Comment by myronkscott** [comment]
I see.  So This is not related to the other issues.  This is something entirely different.  It will involve some serious rearrangement of code in the platform to change this but I think we can do it.  In the future it would be ideal not to link these two event streams (platform provided events vs. entity api event callbacks) so directly.  Both independent streams will be properly sequenced but they may not interleave the same way.  This is probably a future discussion.

**Comment by mathieucarbou** [comment]
Agree. But what I asked for in the first beginning was to be aware, on client-side, when the client has reconnected.
This is the only thing we need. And if we have that, it would solve the issue because client reconnection comes after reconnectData.
Currently, we try to hack something by using the reconnect data as Jeff told us since we do not have a callback on client-side when a client has reconnected.
So for us, reconnect data is clearly not the way to go. Especially because on client-side, things could have changed about the management registry. So it is more reliable to us if we had a way to know on client side when the client has reconnected, instead of having a callback requesting for some reconnect data.

**Comment by mathieucarbou** [comment]
@myronkscott : is it ready to test against new tc-core master snapshot ?

**Comment by myronkscott** [comment]
you can git it a shot yes

**Comment by mathieucarbou** [comment]
@myronkscott : confirmed! it works! thanks :-)
