### ISSUE TITLE
Intermittent TCWorkerCommManagerTest>TCTestCase.runBare:196->testWorkerCommDistributionAfterReconnect:377 Expected <2> but got <3>

### ISSUE THREAD

**Issue by jd0-sag** [Terracotta-OSS/terracotta-core#414]
This is seen very rarely:

```
-------------------------------------------------------------------------------
Test set: com.tc.net.core.TCWorkerCommManagerTest
-------------------------------------------------------------------------------
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.256 sec <<< FAILURE! - in com.tc.net.core.TCWorkerCommManagerTest
testWorkerCommDistributionAfterReconnect(com.tc.net.core.TCWorkerCommManagerTest)  Time elapsed: 3.436 sec  <<< FAILURE!
com.tc.util.TCAssertionError: Expected <2> but got <3>
        at com.tc.net.core.TCWorkerCommManagerTest.testWorkerCommDistributionAfterReconnect(TCWorkerCommManagerTest.java:377)
```

My initial suspicion is that this is either a race between the connection threads and the test thread (since the test is multi-threaded) or that some environmental issue caused a connection to not close when the test expected.

Note that there is a timeout in the connection which must be disabled in order to debug this:  `ClientMessageTransport.java:277`

**Comment by jd0-sag** [comment]
I think that the problem is a race to assign connections to worker threads.  If this is true, it probably isn't a problem (we could fix it but that would add some overhead to the connection path - probably not worth the benefit of a more perfect thread balance) and we likely just need to change the test to verify that all the connections are accounted for, not necessarily perfectly balanced across threads (or change the test to connect them serially).

Since this is intermittent, I will augment the test with more information and proceed with other matters.  That way, we can pick this up with more information, when it is next observed.

**Comment by jd0-sag** [comment]
While preparing this change for PR, I hit the bug again.  The weights were 3, 1, 2 instead of the expected 2, 2, 2.  This does mean that we have the correct total number of connections but that they are distributed incorrectly.  This would be what we see in response to the race condition I suggested, above.

I will look into proving whether or not that can happen, as an explanation.

**Comment by myronkscott** [comment]
Timebombed the test until Feb 1.  This code needs to be reworked.

**Comment by myronkscott** [comment]
Covered by #425.
