### ISSUE TITLE
loadExisting() not called in right order (after addNode) after a failover

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/terracotta-core#426]
We are using the Entity `createNew()` method as suggested by @jd0-sag to do some actions related to the monitoring tree after an entity is created. This is the only place where we can because the steps are like below:

1. Server entity creation (createActiveEntity())
2. addNode() from platform
3. Entity.createNew() is called by platform
4. We can then interact with some M&M services and complete the topology because the tree is ready

This the createNew() method call is important for us because we are not aware in the entity construction of the event in the monitoring tree, but after. So there has been an ordering discussed about that (in chatroom) so that platform does the addNode() after createActiveEntity() but before createNew().

Sadly, during a failover, this step is missing.

1.  Election manager declares winner (ACTIVE-COORINDATOR logging that you see)
but the server is not fully active yet.  That log message only starts the process
2.  Passive entities are removed
3.  Active entities are created
4.  Server declared active to M&M and cached tree replayed
5.  Reconnect window opens
6.  Clients reconnect
7.  Reconnect window closes. transition completed to active server. now ready to process new transactions

After step 4, there should be a call to `createNew()` on newly created entities, but this call is missing. We only see the `createActiveEntity()` method called, followed by some `addNode()`. But no "initialization" method is called.

This is a bug that @anthonydahanne reported by testing with the TMS and preventing us at this time to release the TMS with failover support.

__UPDATE 1__

FYI, here is the bug reported by @anthonydahanne (https://github.com/Terracotta-OSS/terracotta-platform/issues/252) and a PR to replay it (https://github.com/Terracotta-OSS/terracotta-platform/pull/253 - `FailoverIT.management_call_and_stats_after_failover`)

**Comment by jd0-sag** [comment]
After failover, you will get a `loadExisting()` call, instead of `createNew()`.

**Comment by mathieucarbou** [comment]
ok! I'll have a look! thanks for the fast reply!

**Comment by mathieucarbou** [comment]
@jd0-sag : `loadExisting()` does not work because it is called after `createActiveEntity()` but before the tree data is created / inserted. So we cannot initialize anything and expose anything on top of the missing node that we expect to be there, like it is with `createNew()`.

**Comment by mathieucarbou** [comment]
@myronkscott : it is because entity information is completing the tree structure that is built thanks to the platform. And it is not possible to expose additional information in the m&m topology if the topological elements holding this information is not there.

Until now, everything was fine: we were able to rely on platform events and even some ordering that we discussed in the chatroom. We designed the M&M solution also based on this fact that we knew platform wils send us some events before other ones. 

If you say we have to change all what we did, we will need a discussion that will involve PM because it's a complete rewriting.

Also, before doing that, perhaps it's time to ask for a full __platform specification / doc regarding all the lifecycle, ordering, states happening in platform__. Platform has always been a black box and we don't know well how it works and on what we can rely for M&M. We always have to do some hacks and workaround because we don't get what we really need.

We already rewrote this monitoring service several times because of undocumented behaviors that we faced. The current implementation works fine, except for this ordering on failover. 

We had a lot of discussions in the chatroom, and as I see know, I cannot rely on things we were relying on before.

Sadly I do not see any workaround that can be quickly done for that. The thing we built is not done in a way that entities can "replace" platform and sends entity creation / destruction events instead of platform.

So a broader discussion has to take place somewhere I think because I won't spend several days trying to implement a workaround for something that we thought was provided by platform. If we have to change something, I thing the first step is to get some doc about what platform does, its states, its event ordering, etc, so that we know the things we can rely on or not.

An idea @ljacomet had is to shortcut this `IStripeMonitringService` service , and I think will be safer perhaps for us. If we get rid of this `IStripeMonitringService` and instead provide a management lib that all entities wanting mangement will use, then entities will send events by themselves to the monitoring service for each entity destruction, creation, init, client connection and disconnection.

I think this will solve a lot of issues we have with the use of platform, but will couple all entities to management. But perhaps it's safer. I don't know. 

Anyway, I think @anthonydahanne @ljacomet and you guys need to have a discussion about all that because the situation is REALLY frustrating for me that always have to re-do things all the time!

**Comment by myronkscott** [comment]
The basic issue is that you are tightly bounding all events in your system where you are relying on a specific sequence of events to always arrive into the tree in a serial order.  This is not a single threaded system.  We have provided platform facades that do late binding and fake specific sequences for things like entity fetches to ease M&M integration but that is within one API (the platform events API).  

Now you are saying that you require exact sequencing between two **different** APIs.  Entity API and platform events API.  We have said from the beginning that each event, whether Entity API or platform events API should be treated atomically, each on there own as much as possible.  Entity create/destroy and entity fetch from the platform API cannot be expected to have an exact sequence with Entity API createNew or loadExisting.  These are two separate APIs with separate purposes.  If you would like to create associations between the two, do so with **late binding**.  

M&M must consume events from many different sources and make some sense of what the system is doing.  I understand it is not an easy job but you are trying to mandate and lock in a very specific behavior and sequencing from the platform that is unrealistic in a multi-threaded multi-process system.  This is very frustrating from platform side as hidden sequencing requirements appear and get reported as bugs which they are clearly not.  Instead of tightly coupling events to make them fit into the tree.  Why not store all the data needed and bind together what you need at time of query instead of when the event is produced?  Forgive me if this is naive, I clearly don't have an understanding of what you are trying to build.

I'm not sure I understand the idea around not using IStripeMonitoring.  That is simply an event delivery service.  This is also how you are going to get information from passives to TMS.  Issues of sequence ordering will not go away by putting a high level API around or on top of that.  Events will still be delivered from various threads in various orders based on calls into the entity.

**Comment by myronkscott** [comment]
@mathieucarbou : nothing mandates that additional information must go in specific places within the tree structure.  In fact, if events are produced by another API, they probably should have their own structure from their own root.  Put them in their own hierarchy and associate the elements as needed at the time of query.

**Comment by mathieucarbou** [comment]
I would have like to have all this information several months ago when we started to develop the monitoring service. We were given no guidelines at all about the event, ordering or anything related to lifecycle of entities. So it's easy to pinpoint the wrong things after what's done (and perhaps in a wrong way). I think we've done the best we could with the information we had.

Now if this is the time to redo things, I'll let PM decide but not me. I start to be really tired of this service and the fact that we always need to change or adapt because we do not have the right information. Trying to bridge the voltron side and the M&M side is hard.

I really wish someone else will take over what I did to see the difficulties and understand them and perhaps come with different implementation. There's a lot of constraints (topology, notif, stats, client-side and entity-side management metadata, contextual routing, etc) and if I were able to just throw all events received to the TMS, of course I would have done that.

**Comment by myronkscott** [comment]
I understand that you are frustrated.  I am not trying to assign blame or argue.  You have a hard job.  No other service has to mesh the extra information that is presented to M&M and I can understand how it would seem natural to merge those two event streams.  

From the platform side we are trying to guarantee a consistent and predictable event stream on Entity API and separately on the platform events presented to monitoring.  See #428.  What we can't guarantee is that these two streams will mesh is some consistent and predictable fashion.  It will mostly be the same but as you can see from this issue, it will break in subtle ways.  

If you would like to discuss workarounds or solutions, I'm eager to help and discuss.  This simply is not something that we can fix solely from the platform side.

**Comment by mathieucarbou** [comment]
The only quick workaround I found is for the moment to enable an entity to fetch a sort of `EventListenerService` so that an entity can register a callback in its fetched service to listen on entity creation, destruction, etc as the monitoring service gets aware of them.

Example:

```
  @Override
  public ActiveCacheServerEntity createActiveEntity(ServiceRegistry registry, String identifier) {
    LOGGER.trace("createActiveEntity({})", identifier);
    [...]

    // workaround for https://github.com/Terracotta-OSS/terracotta-core/issues/426
    EntityEventService entityEventService = Objects.requireNonNull(registry.getService(new BasicServiceConfiguration<>(EntityEventService.class)));
    entityEventService.addEntityEventListener(new EntityEventListenerAdapter() {
      @Override
      public void onCreated() {
        LOGGER.trace("[{}] onCreated()", identifier);
        management.init();
        management.serverCacheCreated(cache);
      }
    });

    return new ActiveCacheServerEntity(cache, management);
  }
```

I am testing it. This is very ugly on user-side, but its the only way I found and that is quick to do to ensure a monitoring initialization after platform sent us the events.

**Comment by myronkscott** [comment]
That seems problematic.  Your code will register the event listener every time an entity is created.  Nothing unregisters the listener when the entity is destroyed.  You will end up holding a bunch of references to dead objects.

**Comment by mathieucarbou** [comment]
they are unregistered when entity is destroyed or when server became active from within the monitoring service.
This is a user-friendly interface. It's not true that things are not unregistered because there are no "unregister" methods: it's just done another way, and avoids also the user to be responsible of that if he forgot.

**Comment by myronkscott** [comment]
As designed.  We will discuss solutions to current implementations
