### ISSUE TITLE
ASL 2.0

### ISSUE THREAD

**Issue by sirinath** [Terracotta-OSS/terracotta-core#441]
Is it possible to move the whole project to ASL 2.0 including core?

Also perhaps worth while considering is moving to ASF which would ensure the contribution are from multiple parties than 1 source and commitment to be open source. I am not affiliated to ASF.

**Comment by ljacomet** [comment]
Hello,

Thanks for your interest in Terracotta.

We request that users start the conversation on the [google group terracotta-oss](https://groups.google.com/forum/#!forum/terracotta-oss) before opening issues.

***

Now to your point, there is no project of doing that. I sincerely hope this does not prevent from using the code, the product or even start contributing.

Closing as _not doing_.

**Comment by sirinath** [comment]
Is it possible to consider a ASL 2.0 compatible permissive licence?
