### ISSUE TITLE
Implement setNewConcurrencyStrategy for entities

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-core#49]
Entities should be able to set a new ConcurrencyStrategy while active.  Any change in concurrency strategy needs to be tightly coordinated with the platform so no other operation including sync is happening on the entity while the new ConcurrencyStrategy is being installed.

setConcurrencyStrategy should be a top level, ManagedEntity function.

**Comment by jd0-sag** [comment]
While we eventually would like to support this, it is well outside the scope of our current concerns.
