### ISSUE TITLE
Investigate Entity Exception propagation to the client

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-core#509]
If an entity server component throws an exception, it will bring down the server.  Investigate a system of exception propagation to the client in a standard way.

**Comment by jd0-sag** [comment]
Is our starting assumption that only the active will throw the exception back to the client but an uncaught exception will still bring down a passive?

**Comment by myronkscott** [comment]
I would like to use the opt in model where EntityUserException is propagated to the client from the active and ignored on the passive.  Any other runtime exception will bring down the server for now.  That is my preference.

**Comment by jd0-sag** [comment]
Hmm, that is an interesting approach.  Does seem viable so long as we can get buy-in from the downstream components.
