### ISSUE TITLE
Retirement Handles

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-core#510]
Investigate giving entity implementors the ability to delay retirement response until they explicitly use a retirement handle to close the message scope manually on their own.

**Comment by jd0-sag** [comment]
Just something to point out is that we will need to ensure there is good diagnostic visibility into these handles since leaking them or being slow to retire them will cause client-side issues.

**Comment by cschanck** [comment]
OK, PR out for anzadocs, merged. PR out for -apis, awaiting commentary. I have working unit tests, impl, etc, in core ready to go. I have passthrough-testing changed as well. Still struggling with terracotta-integration testing, but it will come.

**Comment by myronkscott** [comment]
PR #537
