### ISSUE TITLE
Remove DumpServer class and associated dependencies

### ISSUE THREAD

**Issue by chrisdennis** [Terracotta-OSS/terracotta-core#514]
The DumpServer main class is a vestige of when we had a command line script to dump the server contents. My understand is that this is now to be accomplished through the dump server entity.  Eliminating this class will also allow for the removal of the JLine and Apache Commons CLI dependencies.

**Comment by jd0-sag** [comment]
It looks like we can get rid of `DumpServer`, a few other classes related to command-line interaction, and the JLine dependency.  However, Commons CLI is used by `StandardConfigurationSetupManagerFactory` which is used directly by `TCServerMain`.
