### ISSUE TITLE
Need PlatformService's dumpPlatformState() like API in Diagnostics

### ISSUE THREAD

**Issue by saurabhagas** [Terracotta-OSS/terracotta-core#545]
Diagnostics' getThreadDump() API returns the thread dump as a String. There are scenarios where it is needed to dump the server state in the default server logs' location, much like PlatformService's dumpPlatformState() does. An additional method in Diagnostics which could provide that functionality would be useful.

**Comment by myronkscott** [comment]
```Diagnostics.invoke("L2Dumper","doServerDump")``` should do what you desire.  If this is not the case, please reopen this issue.

**Comment by saurabhagas** [comment]
Worked like a charm! Thanks.
