### ISSUE TITLE
Rationalize Cluster Dump

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-core#551]
Cluster Dump needs to be analyzed for proper information in the proper format.  Study the current format.  Make sure important internal platform system information is presented as well as proper delegation to entities and services.

**Comment by ramsai1729** [comment]
Cluster State dump has following components state

- StageManager
- Persistor
- GroupManager
- L2Coordinator
- EntityManager
- ServiceRegistry

However Persistor, EntityManager and ServiceRegistry state is not complete. I am working on following tasks currently

- Add more details for Persistor state (ClientStatePersistor, EntityPersistor and TransactionOrderPersistor states)
- Force Server Entity implementations to extend Dumpable interface to collect entity state and same goes for Service providers

Next items to work on:

- Clients state dump 
- Clean up cluster State collection process (Diagnostic getCluserState vs Dumper entity) 
- Improve other existing components state information

**Comment by myronkscott** [comment]
Can you clarify 

1. Clients state dump
2. Clean up cluster State collection process (Diagnostic getCluserState vs Dumper entity)

I do not think 1 is possible and I dont understand 2

**Comment by ramsai1729** [comment]
1. Clients state dump

I have not thought through this fully, but my initial thinking is to fetch a helper entity (which is capable of generating thread dumps etc) by default (once per connection, need to think about multiple connections though) and use ClientCommunicator service whenever a dump is requested. However, we need a mechanism to dump platform state on the client side and other entities state etc

2. Clean up cluster State collection process (Diagnostic getCluserState vs Dumper entity) 

Currently we have two ways to generate cluster state - Diagnostics.getClusterState() and PlatformService.dumpPlatformState(), both collect/dump cluster state but in different forms (string and dumping to logs). May be we can rid of one way and collect state from all components only once and transform to other formats as needed.

**Comment by myronkscott** [comment]
1.  sounds reasonable

2.  I'm not sure that we don't need both versions.  The diagnostic port for some situations, the entity for others.  Maybe we can get rid of the platformservice and just opt for the MBean.  not sure.

**Comment by ramsai1729** [comment]
cleanup work is done in #620
