### ISSUE TITLE
Semantics of getService / getServices

### ISSUE THREAD

**Issue by ChrisGreenaway** [Terracotta-OSS/terracotta-core#584]
It seems that ServiceRegistry.getServices() only gets "external" services - i.e. not built in platform provided services. I would have expected to be able to use it to get any kind of services. This either needs some Javadoc or needs a fix. My preference would be for a fix.

Also, getService() returns null when there is no such service. I personally think it would be better if it threw an Exception in this case. We could always have a getPossibleService() that returns null, if that's desired. However, if nothing else, the behaviour (e.g. returning null) should be documented.

**Comment by myronkscott** [comment]
Builtin services are "special" services that there is never expected to be more than one.  We toyed with getting rid of getService() all together and making everyone rely on getServices().   If we had done that, then getServices() would have had to return both builtin and external services.

There were several discussions with downstream about whether "one and only one" (throw exception) or "at most one" (return null) semantics was correct.  The consumers had strong opinions that "at most one" was correct so existing behavior was maintained in the latest iteration.

**Comment by henri-tremblay** [comment]
Indeed, we decided against throwing an exception. Because you can ask for an optional service. So returning null and letting the caller deal with the result is the most flexible solution. But, of course, obviously, indeed, it should be documented.
