### ISSUE TITLE
Serialization problems with ClientDescriptor

### ISSUE THREAD

**Issue by ChrisGreenaway** [Terracotta-OSS/terracotta-core#648]
We should use something like runnel to implement the Serialization of ClientDescriptor to avoid problems with upgrading.

**Comment by ChrisGreenaway** [comment]
There are also security issues with deserializing arbitrary bytes which could be sent by an attacker.

**Comment by ChrisGreenaway** [comment]
I think the security issues rule out using any kind of serialization (with or without runnel) for transferring objects from active to passive.

**Comment by myronkscott** [comment]
ClientDescriptor is never directly serialized in the platform.  Consumers of the API may choose to serialize it but that is up to them.  We will look at ways accessing the important identifiers directly so they can avoid direct serialization

**Comment by myronkscott** [comment]
ClientDescriptor is no longer Serializable
