### ISSUE TITLE
Do something smart if an entity implementation is not complete

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-core#68]
Currently if an entity implementation is not complete the platform fails in strange and not obvious ways.  For example, if ServerEntityService throws an UnsupportedOperation, the platform does not complain and behavior is then undefined.  Errors and unchecked exceptions from Entity code must be handled in deterministic and consistent ways.

**Comment by myronkscott** [comment]
Force complete system failure if some part of the Entity API is not implemented or incomplete

**Comment by myronkscott** [comment]
This is related to exception handling work.  Please take a look.

**Comment by ramsai1729** [comment]
Looks like this issue is already taken care in issue #55
