### ISSUE TITLE
Add a meaningful log message when diagnostics handler fails

### ISSUE THREAD

**Issue by rkavanap** [Terracotta-OSS/terracotta-core#694]
When generic services are written that are not marked with BuiltIn, it may deploy those services only if the services are configured within platform. And if these services are not deployed, the corresponding JMX attributes and methods of that service may not be registered. 

This issue is for tracking of printing a meaningful warning message (in addition to what is already logged) to the log file, so that the end user (such as an admin) will get a clue about the failure reason.

**Comment by myronkscott** [comment]
PR #697
