### ISSUE TITLE
OSGi support on the client side

### ISSUE THREAD

**Issue by ljacomet** [Terracotta-OSS/terracotta-core#713]
In order to support OSGi on the client side, where the `client-runtime` jar will not have class loading visibility in the jars providing entity implementations, the [linked code](https://github.com/Terracotta-OSS/terracotta-core/blob/ccaefd23d0953dcd38fc58b04379a58b8f5c1bb1/connection-impl/src/main/java/com/terracotta/connection/TerracottaConnection.java#L72)  needs to be adapted so that it uses the class loader of the requested entity class.

This will allow proper lookup as we can expect that the passed in class lives close (in the same OSGi module) or at least has visibility into the module carrying that service implementation.

If that is not the case, I am not sure there is anything we can do outside of supporting a service loading mechanism that is changed based on the runtime execution environment.

**Comment by myronkscott** [comment]
PR #715
