### ISSUE TITLE
Concurrency key in invoke context of passive sync messages are invalid

### ISSUE THREAD

**Issue by albinsuresh** [Terracotta-OSS/terracotta-core#740]
`InvokeContext.getConcurrencyKey()` is returning -1 for sync messages on passive.

**Comment by myronkscott** [comment]
This is as designed since this message is coming from sync rather than IEntityMessenger or a client.  In addition, the concurrency key is included in the call to `SyncMessageCodec.decode()`.  Is this insufficient to your needs?

**Comment by albinsuresh** [comment]
Ooh... too late to reply. Yes I guess I could have used the concurrency key info from the decode method even though the usage would have looked a bit weird. But since this is done already I guess it doesn't matter. Thanks.
