### ISSUE TITLE
ManagedEntity invoke pathways require better organization to handle message types

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-core#8]
ManagedEntity handles every action down a single invoke path.  This can be better organized to handle different message types still utilizing a single execution path but more clearly handling different message types.

**Comment by jd0-sag** [comment]
Are we sure that that is _better_ or just creating new ways of doing the same thing?

I think that we may need to observe what makes sense for entities, as they are developed, and tailor our approach to what pattern emerges.  The current approach may not be right but is at least not prematurely over-designed.
