### ISSUE TITLE
Don't track client-active connections in the passive's ITopologyEventCollector

### ISSUE THREAD

**Issue by jd0-sag** [Terracotta-OSS/terracotta-core#84]
Currently, we suspect that the notification used to collect client connect/disconnect events for ITopologyEventCollector is generating these events for client interactions with the active even when running on the passive.

Ideally, the passive only knows what is _actually_ connected to it so we need to determine a more constrained way of getting this data, such that we only get client data on the active.  Additionally, we either need specific tests for this or more exhaustive assertions in the implementation to ensure that the passive never sees these client connections.

**Comment by jd0-sag** [comment]
Assigning to Myron since he already fixed this under another item.

**Comment by myronkscott** [comment]
Fix was merged with PR#123
