### ISSUE TITLE
taracotta-parent inaccessible

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-core#9]
dependency on terracotta-parent 5.0.0.alpha1 dependency is inaccessible.  A new version of [taracotta-parent](https://github.com/Terracotta-OSS/terracotta-parent) needs to be published and the dependency should be updated here.

Once this dependency is fixed.  This repository should be built on cloudbees and published publicly

**Comment by myronkscott** [comment]
https://github.com/Terracotta-OSS/terracotta-parent/issues/5

**Comment by ljacomet** [comment]
Nothing to do here, the terracotta repository information is already present in the root pom.
