### ISSUE TITLE
Deleted values from List, Set, Queue could be reappear because of a network partition

### ISSUE THREAD

**Issue by c0d34** [Terracotta-OSS/terracotta-core#906]
version: 4.3.4
Affected data structures: List, Set, Queue

A network partition between the servers could result in restoring deleted values in List, Set, Queue data structures.

steps to reproduce:
1. setup a cluster with three servers s1, s2, s3 and two clients c1,c2
2. populate a list with some values
3. cut the network between (the primary node + c1) and (the other 2 servers + c2)
4. let c1 and c2 delete some values from the list you populated in step 2
5. fix the network
6. read all values from the list you deleted from in step 4. you would notice that some values are not deleted.

**Comment by myronkscott** [comment]
4x tc-server is not tracked here. The 5.0 tc-core line being developed here is a major break from that code line. That being said, 4x line does not support split brain prevention but if you would still like to report it and track it, http://jira.terracotta.org is the correct place.
