### ISSUE TITLE
Strong consistent cache with synchronous writes can return stale data during a network partition

### ISSUE THREAD

**Issue by c0d34** [Terracotta-OSS/terracotta-core#907]
version: 4.3.4

A network partition between the servers could result in allowing a strong consistent cache with  synchronous writes to return stale or old data.

steps to reproduce:
1. setup a cluster with three servers s1, s2, s3 and two clients c1,c2
2. populate a cache with some value
3. cut the network between (the primary node + c1) and (the other 2 servers + c2)
4. let c2 put some new value to the cache
5. let c1 read the value, it will return the old value

**Comment by myronkscott** [comment]
4x tc-server is not tracked here. The 5.0 tc-core line being developed here is a major break from that code line. That being said, 4x line does not support split brain prevention but if you would still like to report it and track it, http://jira.terracotta.org is the correct place.
