### ISSUE TITLE
Race condition in shutting down hook without closing entities

### ISSUE THREAD

**Issue by rkavanap** [Terracotta-OSS/terracotta-core#911]
If the client does not close its connection and shutsdown.. some exceptions as shown below is seen.

This race is typically seen ONLY in very slow systems and that too occassionally and that too if the client has not shutdown/closed the entity before shutting down...

[Clients][client_setup] 	at org.ehcache.clustered.client.internal.store.SimpleClusterTierClientEntity.fireDisconnectionEvent(SimpleClusterTierClientEntity.java:117)
[Clients][client_setup] 	at org.ehcache.clustered.client.internal.store.SimpleClusterTierClientEntity$1.didDisconnectUnexpectedly(SimpleClusterTierClientEntity.java:105)
[Clients][client_setup] 	at com.terracottatech.connection.disconnect.DisconnectDetectingDelegate.didDisconnectUnexpectedly(DisconnectDetectingDelegate.java:70)
[Clients][client_setup] 	at com.tc.object.EntityClientEndpointImpl.didCloseUnexpectedly(EntityClientEndpointImpl.java:312)
[Clients][client_setup] 	at com.tc.object.ClientEntityManagerImpl.shutdown(ClientEntityManagerImpl.java:373)
[Clients][client_setup] 	at com.tc.object.handshakemanager.ClientHandshakeManagerImpl.shutdownCallbacks(ClientHandshakeManagerImpl.java:193)
[Clients][client_setup] 	at com.tc.object.handshakemanager.ClientHandshakeManagerImpl.shutdown(ClientHandshakeManagerImpl.java:93)
[Clients][client_setup] 	at com.tc.object.ClientShutdownManager.closeLocalWork(ClientShutdownManager.java:94)
[Clients][client_setup] 	at com.tc.object.ClientShutdownManager.execute(ClientShutdownManager.java:75)
[Clients][client_setup] 	at com.tc.object.DistributedObjectClient.shutdownClient(DistributedObjectClient.java:676)
[Clients][client_setup] 	at com.tc.object.DistributedObjectClient.shutdown(DistributedObjectClient.java:698)
[Clients][client_setup] 	at com.tc.object.DistributedObjectClient.access$1100(DistributedObjectClient.java:125)
[Clients][client_setup] 	at com.tc.object.DistributedObjectClient$ShutdownAction.run(DistributedObjectClient.java:708)
[Clients][client_setup] 	at java.lang.Thread.run(Thread.java:748)

**Comment by myronkscott** [comment]
Isn't that what we want?  I'm not seeing how this is a race

**Comment by myronkscott** [comment]
I believe this is what we want.  closing this issue.  If you have more information please reopen and amend.
