### ISSUE TITLE
Use distinguished ConnectionClosedException when message not enqueued

### ISSUE THREAD

**Issue by cljohnso** [Terracotta-OSS/terracotta-core#932]
`ClientEntityManagerImpl` currently throws a `ConnectionClosedException` when sending a message and either the connection was closed _before_ the message was enqueued or _after_ the message was enqueued and may (or may not) have been sent.  For applications attempting resiliency through reconnection, being able to tell the difference between a message that failed before sending and one that failed after sending could be used to improve resiliency operations.

Changing `ClientEntityManagerImpl` to throw a `ConnectionClosedBeforeSendingException` (or something like that), a subclass of `ConnectionClosedException`, to distinguish an unsent message from one that might have been sent would be helpful.

This, of course, would need to be paired with the addition of the exception to Terracotta-OSS/terracotta-apis.  (See Terracotta-OSS/terracotta-apis#298)

**Comment by myronkscott** [comment]
Would a check method on the exception suffice versus a whole new exception class?

**Comment by myronkscott** [comment]
fixed in df4d103ab7
