### ISSUE TITLE
Client leaks memory

### ISSUE THREAD

**Issue by lorban** [Terracotta-OSS/terracotta-core#959]
`DistributedObjectClient` registers a shutdown hook which has the side-effect of adding a reference to some of our objects to the JVM's root class loader.

Not only this leaks a few objects each time a client is closed and re-created, but each time a web app is being redeployed in a web container like Tomcat, the whole webapp's class loader is leaked.

See: https://github.com/Terracotta-OSS/terracotta-core/blob/3b0296a9a1c6877bcc5c3c8398b6479a43fef356/dso-l1/src/main/java/com/tc/object/DistributedObjectClient.java#L186

**Comment by myronkscott** [comment]
This particular code has been in place for a long time to ensure that all local work is flushed to the server before the client goes away.  I am fine removing this as I believe it is of limited value, but it is a change in long standing behavior.

**Comment by myronkscott** [comment]
I'm not sure I understand the leak of this.  The shutdown hook is unregistered if the client is closed so things should be cleaning up properly.

https://github.com/Terracotta-OSS/terracotta-core/blob/3b0296a9a1c6877bcc5c3c8398b6479a43fef356/dso-l1/src/main/java/com/tc/object/DistributedObjectClient.java#L702-L707

**Comment by lorban** [comment]
Right, I overlooked that. Sorry for the noise.

**Comment by myronkscott** [comment]
We are still planning on removing the shutdown hook as it has no good use case.
