### ISSUE TITLE
Consistency manager regression

### ISSUE THREAD

**Issue by esebasti** [Terracotta-OSS/terracotta-core#966]
Can you check this as requiring all servers to be running during startup is not valid for 3 servers cluster.

 if (mode == ServerMode.START && newMode == Transition.MOVE_TO_ACTIVE) {
//  only other servers can be considered in this case.  Only go active 
//  if all servers are present.  any registered
//  external voters should not be considered because they were registered before 
//  when there should have been no cluster wide active
      if (this.activePeers.size() == peerServers || voter.overrideVoteReceived()) {
        CONSOLE.info("Action:{} allowed because all servers are connected", newMode);
        allow = true;
      } else {
        CONSOLE.info("Action:{} not allowed because not enough servers are connected", newMode);
        allow = false;
      } 
      return allow;
    }

**Comment by myronkscott** [comment]
Are you saying that it is not working?

**Comment by myronkscott** [comment]
This is not a regression.  It is a bug fix.  If we do not do this, there is a possibility of losing data by starting a persisted active which wins election with stale data.  On cluster start, all servers are required to join the cluster so only the most recent active is allowed to start as active.  This is only a requirement on initial start.  A quorum will be maintained with proper counts once the active is allowed to initiate.

**Comment by esebasti** [comment]
I think it happens during warm startup as well

**Comment by myronkscott** [comment]
It should not. Any server started in a cluster with a current active should get zapped and join as passive.

**Comment by myronkscott** [comment]
This is not a bug.  Required to make sure cluster is started from cold restart with the most current version of data
