### ISSUE TITLE
Evaluate logging options

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/terracotta-core#98]
Logging in the platform uses multiple paradigms.  Pick an appropriate model and standardize logging for the platform.

**Comment by jd0-sag** [comment]
This refers to a few angles of this problem.

One is the actual logging library used (Log4J, SLF4J, etc).  One is the internal logger used (TCLogging, TCLogger, etc).  An additional one is pattern used in requesting the logger (name of interface, name of class, etc).

**Comment by jd0-sag** [comment]
Marked this as ready since recent conversations have demonstrated that this is becoming a priority since downstream teams are finding problems with these dependencies.
